version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db

  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./db:/data
    command: ["sqlite3"]
